import Head from "next/head";
import { useRouter } from "next/router";
import loginStyle from "../styles/login.module.css";
import Link from "next/link";
import { useForm } from "react-hook-form";
import { useContext } from "react";
import { AuthContext } from "../context/AuthContext";

export default function Login() {
  const { register, handleSubmit } = useForm();
  const { signIn } = useContext(AuthContext);

  async function handleSigIn(data) {
    await signIn(data);
  }

  const router = useRouter();
  if (typeof window !== "undefined") {
    // código do navegador
    var body = document.getElementsByTagName("body");
    if (router.pathname === "/login") {
      body[0].classList.add("login");
    }
  }

  return (
    <>
      <Head>
        <title>ECOWEB - Dashboard - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="wrapper">
        <div className="row ">
          <div
            className={`col-md-6 ${loginStyle.login_left} bg-gradient-to-r from-sky-500 to-blue-900`}
          >
            <h3 className=" text-4xl">Layout</h3>
          </div>
          <div
            className={`login-box col-md-6 ${loginStyle.login_right}  pt-20 pb-20`}
          >
            <div className="login-logo">
              <a href="../../index2.html">
                <b>Admin</b>LTE
              </a>
            </div>

            <div className="card">
              <div className="card-body login-card-body">
                <p className="login-box-msg">
                  Faça o Login para acessar o sistema
                </p>
                <form onSubmit={handleSubmit(handleSigIn)} method="post">
                  <div className="input-group mb-3">
                    <input
                      {...register("identifier")}
                      name="identifier"
                      type="text"
                      className="form-control"
                      placeholder="Email"
                    />
                    <div className="input-group-append">
                      <div className="input-group-text">
                        <span className="fas fa-user"></span>
                      </div>
                    </div>
                  </div>
                  <div className="input-group mb-3">
                    <input
                      {...register("password")}
                      name="password"
                      type="password"
                      className="form-control"
                      placeholder="Password"
                    />
                    <div className="input-group-append">
                      <div className="input-group-text">
                        <span className="fas fa-lock"></span>
                      </div>
                    </div>
                  </div>
                  <div className="row">
                    <div className="col-8">
                      <div className="icheck-primary">
                        <Link href="forgot-password.html">
                          Esqueci a senha!
                        </Link>
                      </div>
                    </div>

                    <div className="col-4">
                      <button
                        type="submit"
                        className="btn btn-primary btn-block bg-blue-500"
                      >
                        Entrar
                      </button>
                    </div>
                  </div>
                </form>
                <div className="social-auth-links text-center mb-3"></div>

                <p className="mb-0">
                  <a href="register.html" className="text-center">
                    Criar uma Conta
                  </a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
